name: Release

on:
  push:
    tags:
      - '*'

jobs:
  sign_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to create GitHub Release
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Sign
        shell: bash
        env:
          SIGNING_PRIVATE_KEY: ${{ secrets.SIGNING_PRIVATE_KEY_BASE64_ENCODED }}
        run: |
          chmod +x ./sign.sh
          ./sign.sh ./YoutubeScript.js ./YoutubeConfig.json
      - name: Get upstream release version
        id: get_upstream_release_version
        uses: actions/github-script@v7
        with:
          script: |
            const upstreamReleaseVersion = '${{ github.ref_name }}'.split('-')[0];
            console.log('Upstream release version:', upstreamReleaseVersion);
            return upstreamReleaseVersion;
          result-encoding: string
      - name: Create draft release and upload plugin files
        id: create_release
        uses: actions/github-script@v7
        with:
          script: |
            const path = require('node:path');
            const fs = require('node:fs/promises');

            const release = await github.rest.repos.createRelease({
              ... context.repo,
              name: 'YouTube with DeArrow (v${{ steps.get_upstream_release_version.outputs.result }})',
              draft: true,
              tag_name: '${{ github.ref_name }}',
              generate_release_notes: true
            });

            console.log('Draft release created:', release.data.html_url);

            for (const fileName of ['YoutubeConfig.json', 'YoutubeScript.js']) {
              console.log(`Uploading ${fileName} asset to draft release`);

              const data = await fs.readFile(fileName);
              await github.rest.repos.uploadReleaseAsset({
                ... context.repo,
                release_id: release.data.id,
                name: fileName,
                data
              });

              console.log(`${fileName} asset uploaded to draft release`);
            }